trigger:
- main

pool: pool1  # Your custom Windows pool

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Building..."
      displayName: 'Build step'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to Environment'
    steps:
    - script: |
        echo "Deployment job running"
      displayName: 'Deploy Job'

- stage: Exit
  dependsOn: Deploy
  jobs:
  - job: Exit
    steps:
    - script: |
        echo "Exiting after deployment"
      displayName: 'Exit step'
